"""create knowledge graph tables

Revision ID: 6c0892d228db
Revises: b0a1f7c4ecf6
Create Date: 2026-10-08 12:21:29.474073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c0892d228db"
down_revision: str | Sequence[str] | None = "b0a1f7c4ecf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_graphs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_graphs_document_id"), "knowledge_graphs", ["document_id"], unique=True
    )
    op.create_table(
        "knowledge_concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.UUID(), nullable=False),
        sa.Column("concept_key", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_chunk_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.ForeignKeyConstraint(["graph_id"], ["knowledge_graphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("graph_id", "concept_key", name="uq_knowledge_concepts_graph_key"),
    )
    op.create_index(
        op.f("ix_knowledge_concepts_graph_id"), "knowledge_concepts", ["graph_id"], unique=False
    )
    op.create_table(
        "knowledge_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.UUID(), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("target_key", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("source_chunk_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.ForeignKeyConstraint(["graph_id"], ["knowledge_graphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_relations_graph_id"), "knowledge_relations", ["graph_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_relations_graph_id"), table_name="knowledge_relations")
    op.drop_table("knowledge_relations")
    op.drop_index(op.f("ix_knowledge_concepts_graph_id"), table_name="knowledge_concepts")
    op.drop_table("knowledge_concepts")
    op.drop_index(op.f("ix_knowledge_graphs_document_id"), table_name="knowledge_graphs")
    op.drop_table("knowledge_graphs")
    # ### end Alembic commands ###
