// Static Tailwind utilities use the shared theme and spacing scale.
// Descendant variants style markup supplied by assistant-ui and react-markdown.
export const ui = {
  fullPageState: 'flex min-h-screen items-center justify-center gap-3 bg-neutral-950 text-sm text-neutral-400',
  app: [
    'group/app grid min-h-screen grid-cols-workspace bg-neutral-950 text-neutral-100',
    'transition-[grid-template-columns] duration-350 ease-panel',
    'data-[sidebar-closed=true]:grid-cols-workspace-closed',
    'data-[graph-open=true]:grid-cols-workspace-graph',
    'data-[sidebar-closed=true]:data-[graph-open=true]:grid-cols-workspace-closed-graph',
    'tablet:grid-cols-workspace-tablet tablet:data-[sidebar-closed=true]:grid-cols-workspace-closed',
    'tablet:data-[graph-open=true]:grid-cols-workspace-tablet',
    'tablet:data-[sidebar-closed=true]:data-[graph-open=true]:grid-cols-workspace-closed mobile:block',
  ].join(' '),
  main: 'flex h-screen min-w-0 flex-col bg-neutral-950',
  sidebar: [
    'flex h-screen flex-col overflow-hidden whitespace-nowrap border-r border-neutral-800 bg-surface',
    'px-3.75 pt-4.5 pb-3.5 transition-sidebar group-data-[sidebar-closed=true]/app:invisible',
    'group-data-[sidebar-closed=true]/app:opacity-0 group-data-[sidebar-closed=true]/app:-translate-x-6',
    'mobile:fixed mobile:top-0 mobile:left-0 mobile:z-10 mobile:w-65',
    'mobile:group-data-[sidebar-closed=true]/app:-translate-x-full',
  ].join(' '),
  sidebarTop: 'flex h-9.5 items-center justify-between',
  sidebarTopActions: 'flex items-center gap-0.5',
  brand: [
    'flex items-center gap-2 pl-1.25 text-lg font-bold tracking-brand text-neutral-50 [&>span]:grid',
    '[&>span]:size-6.75 [&>span]:place-items-center [&>span]:rounded-lg [&>span]:bg-neutral-50',
    '[&>span]:text-neutral-950',
  ].join(' '),
  iconButton: [
    'grid size-8.5 place-items-center rounded-lg border-0 bg-transparent p-0 text-neutral-400',
    'hover:bg-neutral-900 hover:text-white',
  ].join(' '),
  mobileMenu: 'hidden tablet:grid',
  mobileOverlay: 'hidden mobile:fixed mobile:inset-0 mobile:z-9 mobile:block mobile:border-0 mobile:bg-black/75',
  projectSelectLabel: 'mx-2 mt-5.5 mb-1.75 block text-2xs font-bold tracking-eyebrow text-neutral-500',
  projectSelect: [
    'font-mono h-10.5 w-full rounded-lg border border-neutral-700 bg-neutral-900 pr-8.5 pl-2.75 text-xs',
    'text-neutral-100 outline-none focus:border-neutral-500',
  ].join(' '),
  primaryNav: [
    'mt-3.25 grid grid-cols-2 gap-1.5 [&>button]:flex [&>button]:h-9.5 [&>button]:items-center',
    '[&>button]:justify-center [&>button]:gap-1.75 [&>button]:rounded-lg [&>button]:border-0',
    '[&>button]:bg-transparent [&>button]:text-xs [&>button]:text-neutral-500',
    '[&>button:hover]:bg-neutral-900 [&>button:hover]:text-neutral-100',
    '[&>button[data-active=true]]:bg-neutral-900 [&>button[data-active=true]]:text-neutral-100',
  ].join(' '),
  newChat: [
    'mt-5.5 flex h-11.5 w-full items-center gap-2.25 rounded-lg border border-neutral-700 bg-neutral-900',
    'px-3.75 py-0 text-sm font-semibold text-neutral-100 hover:border-accent hover:bg-neutral-900',
  ].join(' '),
  history: 'mt-7',
  historyHeading: [
    'mx-2.5 mb-2 flex items-center justify-between [&>p]:m-0 [&>p]:text-xs [&>p]:font-bold',
    '[&>p]:tracking-label [&>p]:text-neutral-400 [&>button]:border-0 [&>button]:bg-transparent',
    '[&>button]:p-0 [&>button]:text-2xs [&>button]:text-neutral-500 [&>button:hover]:text-neutral-200',
  ].join(' '),
  sidebarSearch: [
    'mt-4 flex h-10.5 items-center gap-2 rounded-lg border border-neutral-700 bg-neutral-900 px-2.5',
    '[&_svg]:shrink-0 [&_svg]:text-neutral-400 [&_input]:min-w-0 [&_input]:flex-1 [&_input]:border-0',
    '[&_input]:bg-transparent [&_input]:text-xs [&_input]:text-neutral-100 [&_input]:outline-none',
    '[&_input::placeholder]:font-mono [&_input::placeholder]:[font-size:inherit]',
    '[&_input::placeholder]:font-normal [&_input::placeholder]:tracking-normal [&_button]:grid',
    '[&_button]:place-items-center [&_button]:border-0 [&_button]:bg-transparent [&_button]:p-0.5',
    '[&_button]:text-neutral-500',
  ].join(' '),
  threadListItem: [
    'group/thread relative [&>button:first-child]:h-10.5 [&>button:first-child]:w-full',
    '[&>button:first-child]:overflow-hidden [&>button:first-child]:rounded-lg',
    '[&>button:first-child]:border-0 [&>button:first-child]:bg-transparent [&>button:first-child]:py-0',
    '[&>button:first-child]:pr-10.5 [&>button:first-child]:pl-3 [&>button:first-child]:text-left',
    '[&>button:first-child]:text-sm [&>button:first-child]:text-ellipsis',
    '[&>button:first-child]:whitespace-nowrap [&>button:first-child]:text-neutral-400',
    '[&>button:first-child:hover]:bg-neutral-900 [&>button:first-child:hover]:text-white',
    'data-[active=true]:[&>button:first-child]:bg-neutral-900',
    'data-[active=true]:[&>button:first-child]:text-white',
  ].join(' '),
  deleteThread: [
    'absolute top-1.75 right-1.75 grid size-7 place-items-center rounded-md border-0 bg-transparent p-0',
    'text-neutral-500 opacity-0 group-hover/thread:opacity-100 group-focus-within/thread:opacity-100',
    'hover:bg-neutral-800 hover:text-white',
    'overflow-hidden text-sm text-left group-data-[active=true]/thread:bg-neutral-900',
    'group-data-[active=true]/thread:text-white',
  ].join(' '),
  sidebarBottom: [
    'mt-auto grid grid-cols-account items-center gap-2 border-t border-neutral-800 px-1.75 pt-3.25',
    'pb-0.75 [&_b]:block [&_b]:text-xs [&_b]:text-neutral-100 [&_small]:mt-0.75 [&_small]:block',
    '[&_small]:text-2xs [&_small]:text-neutral-500 [&_svg]:text-evidence-muted',
  ].join(' '),
  avatar: 'grid size-9 place-items-center rounded-full bg-neutral-100 text-xs font-bold text-neutral-900',
  logoutButton: [
    'grid size-8 place-items-center rounded-lg border-0 bg-transparent p-0 text-neutral-500',
    'hover:bg-neutral-800 hover:text-white',
  ].join(' '),
  header: 'flex h-17 items-center justify-between border-b border-neutral-800 bg-surface px-6',
  headerLeft: 'flex items-center gap-2',
  workspace: 'flex items-center gap-1.5 border-0 bg-transparent text-xs text-neutral-400',
  graphToggle: [
    'flex h-9.75 items-center gap-1.75 rounded-lg border border-neutral-700 bg-neutral-900 px-3.5 py-0',
    'text-xs text-neutral-400 hover:border-neutral-100 hover:bg-neutral-900 hover:text-white',
    'data-[active=true]:border-neutral-100 data-[active=true]:bg-neutral-900',
    'data-[active=true]:text-white mobile:[&>span]:hidden',
  ].join(' '),
  thread: 'min-h-0 flex-1 bg-neutral-950',
  viewport: 'relative flex h-full flex-col overflow-y-auto bg-neutral-950 px-8.5',
  welcome: [
    'mx-auto mt-auto mb-0 w-full max-w-210 pt-17.5 text-center [&>span]:mx-auto [&>span]:mb-5',
    '[&>span]:grid [&>span]:size-11.25 [&>span]:place-items-center [&>span]:rounded-xl',
    '[&>span]:bg-neutral-50 [&>span]:text-neutral-950 [&_h1]:m-0 [&_h1]:text-3xl [&_h1]:font-semibold',
    '[&_h1]:tracking-welcome [&_h1]:text-neutral-50 mobile:[&_h1]:text-2xl [&_p]:mt-2.5 [&_p]:mb-0',
    '[&_p]:text-sm [&_p]:text-neutral-400 [&>div]:mt-7 [&>div]:mb-6 [&>div]:flex [&>div]:justify-center',
    '[&>div]:gap-2 mobile:[&>div]:justify-start mobile:[&>div]:overflow-x-auto [&_button]:rounded-full',
    '[&_button]:border [&_button]:border-neutral-700 [&_button]:bg-neutral-900 [&_button]:px-3.5',
    '[&_button]:py-2.5 [&_button]:text-xs [&_button]:text-neutral-300 [&_button:hover]:border-neutral-500',
    '[&_button:hover]:bg-neutral-900 [&_button:hover]:text-white mobile:[&_button]:shrink-0',
  ].join(' '),
  message: 'mx-auto flex w-full max-w-230 gap-3.5 py-3.75 text-base leading-copy mobile:text-sm',
  userMessage: 'justify-end',
  userMessageStack: 'flex max-w-3/4 flex-col items-end gap-1.5',
  messageAuthor: 'mx-1 mt-0 mb-1.5 block text-right text-2xs text-neutral-500',
  userMessageContent: 'max-w-full rounded-user-message bg-neutral-700 px-3.75 py-2.75 text-white [&_p]:m-0',
  assistantMessage: 'justify-start',
  assistantMark: 'grid size-8 shrink-0 place-items-center rounded-lg bg-neutral-100 text-neutral-900',
  assistantMessageContent: 'max-w-9/10 pt-0.75 text-base whitespace-normal text-neutral-200 [&_p]:m-0',
  footer: [
    'sticky bottom-0 mx-auto mt-auto mb-0 w-full max-w-215 bg-composer-fade pt-6 pb-7 [&>small]:mt-2.25',
    '[&>small]:block [&>small]:text-center [&>small]:text-2xs [&>small]:text-neutral-600',
  ].join(' '),
  composer: 'rounded-2xl border border-neutral-700 bg-neutral-900 p-3.75 shadow-none',
  input: [
    'max-h-40 min-h-14.5 w-full resize-none border-0 bg-transparent p-0.5 text-sm leading-body',
    'text-neutral-100 outline-none placeholder:font-mono placeholder:[font-size:inherit]',
    'placeholder:font-normal placeholder:tracking-normal placeholder:text-neutral-500',
  ].join(' '),
  composerActions: 'mt-1.5 flex items-center justify-end gap-1.75',
  composerScope: 'flex items-center gap-1.5 text-xs text-neutral-500',
  send: [
    'ml-auto grid size-9 place-items-center rounded-lg border-0 bg-white text-neutral-900',
    'disabled:cursor-default disabled:bg-neutral-800 disabled:text-neutral-600',
  ].join(' '),
  processingStatus: [
    'mx-auto flex w-full max-w-190 gap-2.5 py-3.25 text-xs text-neutral-200 [&>svg]:shrink-0',
    '[&_b]:mb-1.75 [&_b]:block [&_b]:text-neutral-100 [&_span]:mr-2.5 [&_span]:inline-flex',
    '[&_span]:items-center [&_span]:gap-1 [&_span]:text-xs [&_span]:text-neutral-400 [&_i]:size-1.25',
    '[&_i]:animate-process-pulse [&_i]:rounded-full [&_i]:bg-neutral-200',
    '[&_span:nth-child(3)_i]:animation-delay-200 [&_span:nth-child(4)_i]:animation-delay-400',
  ].join(' '),
  spin: 'animate-document-spin',
  dialogOverlay: 'fixed inset-0 z-100 animate-dialog-fade bg-black/70',
  dialogContent: [
    'fixed top-1/2 left-1/2 z-101 w-dialog -translate-x-1/2 -translate-y-1/2',
    'animate-dialog-enter rounded-xl border border-neutral-700 bg-neutral-900 p-5.5 text-neutral-100',
    'shadow-dialog',
  ].join(' '),
  dialogTitle: 'm-0 text-lg font-semibold text-neutral-50',
  dialogDescription: 'mt-2.5 mb-0 text-sm leading-body text-neutral-400',
  dialogActions: [
    'mt-6 flex justify-end gap-2.25 [&_button]:h-9.5 [&_button]:rounded-lg [&_button]:px-3.5',
    '[&_button]:py-0 [&_button]:text-xs',
  ].join(' '),
  dialogCancel: 'border border-neutral-700 bg-neutral-900 text-neutral-200 hover:bg-neutral-800',
  dialogDelete: [
    'border border-neutral-100 bg-neutral-100 text-neutral-900 hover:bg-white disabled:cursor-not-allowed',
    'disabled:opacity-40',
  ].join(' '),
  dialogInput: [
    'mt-4.5 h-10.5 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-0 text-sm',
    'text-neutral-100 outline-none focus:border-neutral-500',
  ].join(' '),
  memberIdentity: [
    'mt-4.25 flex items-center justify-between gap-3.75 rounded-lg bg-neutral-950 px-3 py-2.75',
    '[&_span]:block [&_span]:min-w-0 [&_small]:block [&_small]:min-w-0 [&_small]:text-2xs',
    '[&_small]:text-neutral-500 [&_code]:mt-1 [&_code]:block [&_code]:max-w-90 [&_code]:min-w-0',
    '[&_code]:overflow-hidden [&_code]:text-xs [&_code]:text-ellipsis [&_code]:whitespace-nowrap',
    '[&_code]:text-neutral-300 [&_button]:flex [&_button]:h-8 [&_button]:items-center [&_button]:gap-1.5',
    '[&_button]:rounded-md [&_button]:border-0 [&_button]:bg-neutral-100 [&_button]:px-2.5',
    '[&_button]:py-0 [&_button]:text-2xs [&_button]:text-neutral-900',
  ].join(' '),
  memberList: [
    'mt-3.5 max-h-45 overflow-y-auto [&>div]:grid [&>div]:min-h-11.5 [&>div]:grid-cols-member',
    '[&>div]:items-center [&>div]:gap-2 [&>div]:border-t [&>div]:border-neutral-800 [&_span]:block',
    '[&_span]:min-w-0 [&_b]:block [&_b]:min-w-0 [&_b]:text-xs [&_b]:font-medium [&_b]:text-neutral-200',
    '[&_small]:mt-0.75 [&_small]:block [&_small]:min-w-0 [&_small]:overflow-hidden [&_small]:text-2xs',
    '[&_small]:text-ellipsis [&_small]:whitespace-nowrap [&_small]:text-neutral-600 [&_em]:text-2xs',
    '[&_em]:text-neutral-500 [&_em]:capitalize [&_em]:not-italic [&_button]:grid [&_button]:size-7',
    '[&_button]:place-items-center [&_button]:rounded-md [&_button]:border-0 [&_button]:bg-transparent',
    '[&_button]:text-neutral-500 [&_button:hover]:bg-neutral-800 [&_button:hover]:text-white',
  ].join(' '),
  memberForm: [
    'mt-3.75 grid grid-cols-member-form gap-1.75 compact:grid-cols-1 [&_input]:min-w-0 [&_input]:h-9',
    '[&_input]:rounded-lg [&_input]:border [&_input]:border-neutral-700 [&_input]:bg-neutral-950',
    '[&_input]:px-2.25 [&_input]:py-0 [&_input]:text-2xs [&_input]:text-neutral-200',
    '[&_input]:outline-none [&_select]:min-w-0 [&_select]:h-9 [&_select]:rounded-lg [&_select]:border',
    '[&_select]:border-neutral-700 [&_select]:bg-neutral-950 [&_select]:px-2.25 [&_select]:py-0',
    '[&_select]:text-2xs [&_select]:text-neutral-200 [&_select]:outline-none [&_button]:flex',
    '[&_button]:h-9 [&_button]:items-center [&_button]:gap-1.5 [&_button]:rounded-md [&_button]:border-0',
    '[&_button]:bg-neutral-100 [&_button]:px-2.5 [&_button]:py-0 [&_button]:text-2xs',
    '[&_button]:text-neutral-900 [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-35',
  ].join(' '),
  memberError: 'mt-2.25 mb-0 text-2xs text-danger',
  documentsPage: [
    'mx-auto w-documents overflow-y-auto pt-12 pb-17.5 compact:w-documents-mobile',
    'compact:pt-7',
  ].join(' '),
  pageHeading: [
    'flex items-start justify-between gap-5 compact:flex-col compact:items-stretch [&_h1]:m-0',
    '[&_h1]:text-3xl [&_h1]:leading-tight [&_h1]:tracking-title [&_h1]:text-neutral-50 [&_p]:mt-2.25',
    '[&_p]:mb-0 [&_p]:max-w-165 [&_p]:text-sm [&_p]:leading-copy [&_p]:text-neutral-500',
  ].join(' '),
  primaryButton: [
    'flex h-10 shrink-0 items-center gap-2 rounded-lg border-0 bg-neutral-100 px-3.5 py-0 text-xs',
    'font-semibold text-neutral-900 hover:bg-white disabled:cursor-not-allowed disabled:opacity-50',
    'compact:justify-center',
  ].join(' '),
  uploadZone: [
    'mt-8 flex min-h-36 w-full flex-col items-center justify-center gap-2 rounded-xl border border-dashed',
    'border-neutral-700 bg-neutral-950 text-neutral-500 hover:border-neutral-500 hover:bg-neutral-900',
    'hover:text-neutral-200 [&_b]:text-sm [&_b]:font-medium [&_b]:text-neutral-200 [&_span]:text-xs',
  ].join(' '),
  documentPageError: 'mt-3.75 mb-0 text-xs text-danger',
  documentTable: 'mt-6 overflow-hidden rounded-xl border border-neutral-800 bg-surface',
  documentTableHead: [
    'grid h-11 grid-cols-documents items-center gap-3.75 bg-neutral-900 px-4.5 py-0 text-2xs font-bold',
    'tracking-table text-neutral-500 compact:hidden',
  ].join(' '),
  documentTableRow: [
    'grid min-h-16 grid-cols-documents items-center gap-3.75 border-t border-neutral-800 px-4.5 py-0',
    'text-xs text-neutral-400 hover:bg-neutral-900 compact:grid-cols-document-mobile compact:gap-2',
    'compact:py-3.25 compact:[&>span:nth-child(2)]:hidden compact:[&>span:nth-child(3)]:hidden',
    'compact:[&>span:nth-child(4)]:hidden',
  ].join(' '),
  pendingUploadRow: [
    'bg-neutral-900 [&_small]:max-w-135 [&_small]:overflow-hidden [&_small]:text-ellipsis',
    '[&_small]:whitespace-nowrap',
  ].join(' '),
  documentName: [
    'flex min-w-0 items-center gap-2.5 [&>i]:grid [&>i]:size-8 [&>i]:shrink-0 [&>i]:place-items-center',
    '[&>i]:rounded-lg [&>i]:bg-neutral-900 [&>i]:text-neutral-300 [&_span]:block [&_span]:min-w-0',
    '[&_b]:block [&_b]:min-w-0 [&_b]:overflow-hidden [&_b]:text-xs [&_b]:font-medium [&_b]:text-ellipsis',
    '[&_b]:whitespace-nowrap [&_b]:text-neutral-100 [&_small]:mt-1 [&_small]:block [&_small]:min-w-0',
    '[&_small]:text-2xs [&_small]:text-neutral-600',
  ].join(' '),
  documentStatus: [
    'inline-flex rounded-md bg-neutral-800 px-1.75 py-1 text-2xs text-neutral-400 capitalize not-italic',
    'data-[status=ready]:text-neutral-100 data-[status=failed]:text-danger',
    'data-[status=uploading]:text-neutral-200',
  ].join(' '),
  uploadingStatus: [
    'before:mr-1.5 before:size-1.25 before:animate-upload-pulse before:rounded-full before:bg-current',
    'before:content-[\'\']',
  ].join(' '),
  rowActions: [
    'flex justify-end gap-1.25 [&_button]:grid [&_button]:size-7.75 [&_button]:place-items-center',
    '[&_button]:rounded-md [&_button]:border-0 [&_button]:bg-transparent [&_button]:text-neutral-500',
    '[&_button:hover]:bg-neutral-800 [&_button:hover]:text-white [&_button:disabled]:cursor-not-allowed',
    '[&_button:disabled]:opacity-30',
  ].join(' '),
  documentEmpty: [
    'flex min-h-37.5 items-center justify-center gap-2.25 border-t border-neutral-800 text-xs',
    'text-neutral-500',
  ].join(' '),
  graphPanel: [
    'invisible h-screen min-w-0 translate-x-6 overflow-hidden border-l border-neutral-800 bg-surface',
    'opacity-0 transition-panel group-data-[graph-open=true]/app:visible',
    'group-data-[graph-open=true]/app:translate-x-0 group-data-[graph-open=true]/app:opacity-100',
    'tablet:fixed tablet:top-0 tablet:right-0 tablet:z-6 tablet:w-intelligence-panel tablet:shadow-drawer',
  ].join(' '),
  graphHeader: [
    'flex h-17 items-center justify-between border-b border-neutral-800 bg-surface px-5 py-0',
    '[&_b]:block [&_b]:text-sm [&_b]:text-neutral-50 [&_small]:mt-1 [&_small]:block [&_small]:text-xs',
    '[&_small]:text-neutral-500',
  ].join(' '),
  graphHeaderActions: 'flex items-center gap-1.5',
  refreshGraph: [
    'flex h-8.5 items-center gap-1.75 rounded-lg border border-neutral-700 bg-neutral-900 px-2.5 py-0',
    'text-xs text-neutral-300 hover:border-neutral-600 hover:bg-neutral-800 hover:text-white',
    'disabled:cursor-not-allowed disabled:opacity-45',
  ].join(' '),
  intelligenceTabs: [
    'grid h-11.75 grid-cols-2 gap-1.25 border-b border-neutral-800 bg-surface px-3.5 py-1.75',
    '[&_button]:flex [&_button]:items-center [&_button]:justify-center [&_button]:gap-1.75',
    '[&_button]:rounded-md [&_button]:border-0 [&_button]:bg-transparent [&_button]:text-xs',
    '[&_button]:text-neutral-500 [&_button:hover]:bg-neutral-900 [&_button:hover]:text-neutral-100',
    '[&_button[data-active=true]]:bg-neutral-900 [&_button[data-active=true]]:text-neutral-100',
  ].join(' '),
  graphContent: 'h-intelligence-content min-h-0 overflow-hidden bg-surface bg-graph-pattern',
  graphState: 'flex h-full flex-col items-center justify-center gap-1.75 p-6.25 text-center text-sm text-neutral-500',
  generateGraph: [
    'h-10 rounded-lg border border-neutral-600 bg-neutral-100 px-4 py-0 text-xs text-neutral-900',
    'hover:bg-white disabled:cursor-not-allowed disabled:opacity-40',
  ].join(' '),
  graphNode: [
    'w-47.5 rounded-lg border border-neutral-600 bg-neutral-900 px-3.25 py-2.75 font-mono text-xs',
    'leading-detail whitespace-normal text-neutral-200 transition-[width,background] duration-200',
    'hover:border-neutral-500 hover:bg-neutral-900 data-[expanded=true]:max-h-55',
    'data-[expanded=true]:w-75 data-[expanded=true]:overflow-y-auto data-[expanded=true]:text-left',
    'data-[kind=question]:border-neutral-100! data-[kind=question]:bg-neutral-100!',
    'data-[kind=question]:text-neutral-900!',
  ].join(' '),
  graphFlow: [
    'bg-transparent! [&_.react-flow__edge-path]:stroke-neutral-500!',
    '[&_.react-flow__edge-text]:fill-neutral-300 [&_.react-flow__edge-text]:font-mono',
    '[&_.react-flow__edge-text]:text-2xs [&_.react-flow__edge-textbg]:fill-neutral-900',
    '[&_.react-flow__edge-textbg]:fill-opacity-graph-label [&_.react-flow__controls]:border',
    '[&_.react-flow__controls]:border-neutral-700 [&_.react-flow__controls]:shadow-none',
    '[&_.react-flow__controls-button]:border-neutral-700 [&_.react-flow__controls-button]:bg-neutral-900',
    '[&_.react-flow__controls-button]:fill-neutral-200 [&_.react-flow__controls-button]:text-neutral-200',
    '[&_.react-flow__controls-button:hover]:bg-neutral-800',
  ].join(' '),
  insightsView: [
    'h-full overflow-y-auto bg-surface/90 px-5.5 pt-6 pb-15 [&_section+section]:mt-8.5 [&_h3]:mt-0',
    '[&_h3]:mb-3.25 [&_h3]:text-sm [&_h3]:text-neutral-100 [&_article]:grid [&_article]:grid-cols-insight',
    '[&_article]:gap-2.5 [&_article]:border-t [&_article]:border-neutral-800 [&_article]:px-0',
    '[&_article]:py-3.25 [&_article>div]:min-w-0 [&_article_b]:text-xs [&_article_b]:leading-detail',
    '[&_article_b]:text-neutral-200 [&_article_p]:mt-1.25 [&_article_p]:mb-0 [&_article_p]:text-xs',
    '[&_article_p]:leading-copy [&_article_p]:text-neutral-400 [&_article_small]:mt-1.75',
    '[&_article_small]:block [&_article_small]:text-2xs [&_article_small]:text-neutral-600',
  ].join(' '),
  insightNumber: 'grid size-5.75 place-items-center rounded-md bg-neutral-200 text-2xs font-bold text-neutral-900',
  priority: [
    'grid size-5.75 place-items-center rounded-md bg-neutral-200 text-2xs font-bold text-neutral-900',
    'data-[priority=medium]:bg-neutral-700 data-[priority=medium]:text-neutral-200',
    'data-[priority=low]:bg-neutral-800 data-[priority=low]:text-neutral-400',
  ].join(' '),
  actionMeta: [
    'flex flex-wrap items-center gap-1.5 [&_b]:mr-auto [&_em]:rounded [&_em]:border',
    '[&_em]:border-neutral-700 [&_em]:px-1.25 [&_em]:py-0.75 [&_em]:text-2xs [&_em]:text-neutral-500',
    '[&_em]:capitalize [&_em]:not-italic',
  ].join(' '),
  insightsEmpty: 'text-xs text-neutral-500',
  answerEvidence: 'mt-5 border-t border-neutral-800 pt-2',
  answerSources: 'mt-4.25 border-t border-evidence-border pt-3.25',
  evidenceToggle: [
    'flex w-full items-center gap-1.5 border-0 bg-transparent px-0 py-2.75 text-left text-xs',
    'text-neutral-400 hover:text-white [&_svg:last-child]:ml-auto [&_svg:last-child]:transition-rotation',
    '[&_svg:last-child]:duration-180',
  ].join(' '),
  sourceList: 'mb-2.5 grid gap-2',
  sourceCard: [
    'mt-1.5 overflow-hidden rounded-lg border border-neutral-700 bg-neutral-900 [&>button]:grid',
    '[&>button]:w-full [&>button]:grid-cols-source [&>button]:items-center [&>button]:gap-1.75',
    '[&>button]:border-0 [&>button]:bg-transparent [&>button]:p-2 [&>button]:text-left [&>button]:text-xs',
    '[&>button]:text-evidence-text [&>button:hover]:bg-evidence-hover [&_strong]:block [&_strong]:text-xs',
    '[&_strong]:font-medium [&_strong]:text-neutral-200 [&_small]:mt-0.5 [&_small]:block',
    '[&_small]:text-2xs [&_small]:text-neutral-500 [&_svg]:text-evidence-icon',
    '[&_svg]:transition-rotation [&_svg]:duration-180 [&_p]:m-0 [&_p]:pt-0 [&_p]:pr-2.5 [&_p]:pb-2.5',
    '[&_p]:pl-8.75 [&_p]:text-xs [&_p]:leading-body [&_p]:text-neutral-300',
  ].join(' '),
  sourceNumber: 'grid size-5 place-items-center rounded-md bg-neutral-200 text-2xs text-neutral-900',
  reasoningSummary: [
    'mt-0 mb-2 flex flex-wrap items-center gap-1.25 rounded-lg border border-neutral-700 bg-neutral-900',
    'p-2.25 text-xs leading-body text-neutral-300 [&_i]:h-px [&_i]:w-2.5 [&_i]:bg-neutral-600',
    '[&_p]:mt-1.25 [&_p]:mb-0 [&_p]:w-full [&_p]:text-2xs [&_p]:text-neutral-500',
  ].join(' '),
  retrievalChunks: [
    'mt-0 mb-2.5 grid gap-2 [&_article]:rounded-lg [&_article]:border [&_article]:border-neutral-700',
    '[&_article]:bg-neutral-900 [&_article]:p-2.25 [&_header]:flex [&_header]:h-17',
    '[&_header]:items-center [&_header]:justify-between [&_header]:border-b [&_header]:border-neutral-800',
    '[&_header]:bg-surface [&_header]:px-6 [&_header]:text-2xs [&_header]:text-neutral-500',
    '[&_em]:text-neutral-200 [&_em]:not-italic [&_p]:mt-1.5 [&_p]:mb-0 [&_p]:text-xs [&_p]:leading-body',
    '[&_p]:text-neutral-300',
  ].join(' '),
  emptyEvidence: 'm-0 p-2.25 text-2xs text-evidence-muted',
  markdown: [
    'text-base leading-normal text-neutral-200 [&>:first-child]:mt-0 [&_p]:mt-0 [&_p]:mb-1.5',
    '[&_h1]:mt-3.25 [&_h1]:mb-1.5 [&_h1]:text-2xl [&_h1]:leading-heading [&_h1]:text-evidence-heading',
    '[&_h2]:mt-3.25 [&_h2]:mb-1.5 [&_h2]:text-lg [&_h2]:leading-heading [&_h2]:text-evidence-heading',
    '[&_h3]:mt-3.25 [&_h3]:mb-1.5 [&_h3]:text-lg [&_h3]:leading-heading [&_h3]:text-evidence-heading',
    '[&_ul]:mt-0.5 [&_ul]:mb-2 [&_ul]:pl-5 [&_ol]:mt-0.5 [&_ol]:mb-2 [&_ol]:pl-5 [&_li]:my-px',
    '[&_li+li]:mt-1 [&_li>p]:m-0 [&_strong]:text-evidence-heading [&_code]:rounded',
    '[&_code]:bg-evidence-code-surface [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-sm',
    '[&_code]:text-evidence-code [&_pre]:my-3 [&_pre]:overflow-auto [&_pre]:rounded-lg [&_pre]:border',
    '[&_pre]:border-evidence-border [&_pre]:bg-evidence-surface [&_pre]:p-3 [&_pre_code]:bg-transparent',
    '[&_pre_code]:p-0 [&_blockquote]:my-3 [&_blockquote]:mx-0 [&_blockquote]:border-0',
    '[&_blockquote]:bg-transparent [&_blockquote]:p-0 [&_blockquote]:text-evidence-quote',
    '[&_blockquote]:italic [&_table]:my-3 [&_table]:w-full [&_table]:border-collapse [&_table]:text-sm',
    '[&_th]:border [&_th]:border-evidence-border [&_th]:bg-evidence-table [&_th]:px-2 [&_th]:py-1.75',
    '[&_th]:text-left [&_th]:text-evidence-heading [&_td]:border [&_td]:border-evidence-border',
    '[&_td]:px-2 [&_td]:py-1.75 [&_td]:text-left',
  ].join(' '),
  loginPage: 'grid h-screen min-h-screen min-w-0 grid-cols-login bg-neutral-950 text-neutral-100 login-compact:block',
  loginContext: [
    'flex min-h-screen flex-col justify-between bg-neutral-950 bg-login-pattern px-13.5 py-10.5',
    'login-compact:hidden [&>div:nth-child(2)]:max-w-170 [&_p]:mt-0 [&_p]:mb-5 [&_p]:text-xs',
    '[&_p]:font-bold [&_p]:tracking-eyebrow [&_p]:text-neutral-500 [&_h1]:m-0 [&_h1]:max-w-160',
    '[&_h1]:text-hero [&_h1]:leading-hero [&_h1]:tracking-hero [&_h1]:text-neutral-50 [&_h1+span]:mt-6',
    '[&_h1+span]:block [&_h1+span]:max-w-132.5 [&_h1+span]:text-base [&_h1+span]:leading-relaxed',
    '[&_h1+span]:text-neutral-400 [&>small]:text-xs [&>small]:text-neutral-500',
  ].join(' '),
  loginBrand: [
    'flex items-center gap-2.75 font-mono text-lg font-bold [&>span]:grid [&>span]:size-10.5',
    '[&>span]:place-items-center [&>span]:rounded-xl [&>span]:bg-neutral-100 [&>span]:text-neutral-900',
  ].join(' '),
  loginPanel: [
    'grid place-items-center bg-surface p-7.5 login-compact:min-h-screen [&_form]:w-login-form',
    '[&_h2]:m-0 [&_h2]:text-3xl [&_h2]:tracking-title [&_h2]:text-neutral-50 [&_h2+p]:mt-2.25',
    '[&_h2+p]:mb-7.5 [&_h2+p]:text-sm [&_h2+p]:text-neutral-500 [&_label]:mt-3.75 [&_label]:grid',
    '[&_label]:gap-2 [&_label]:text-xs [&_label]:font-semibold [&_label]:text-neutral-400',
    '[&_input]:h-11.5 [&_input]:rounded-lg [&_input]:border [&_input]:border-neutral-700',
    '[&_input]:bg-neutral-900 [&_input]:px-3.25 [&_input]:py-0 [&_input]:text-sm',
    '[&_input]:text-neutral-100 [&_input]:outline-none [&_input:focus]:border-neutral-500',
    '[&_form>button]:mt-5 [&_form>button]:h-11.25 [&_form>button]:w-full [&_form>button]:rounded-lg',
    '[&_form>button]:border-0 [&_form>button]:bg-neutral-100 [&_form>button]:font-bold',
    '[&_form>button]:text-neutral-900 [&_form>button:disabled]:opacity-50',
  ].join(' '),
  loginError: 'mt-3 mb-0 text-xs text-danger',
  typingHeadline: 'relative',
  typingMeasure: 'invisible block',
  typingText: 'absolute inset-0',
  typingCursor: [
    'typing-cursor-shape inline-block animate-typing-cursor bg-neutral-50',
    'data-[complete=true]:animate-typing-finish',
  ].join(' '),
} as const
